spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 5d96ee01-e9ea-4609-933f-80c31a72a8c7
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
      datasource:
        ds1.nacos.server-addr: localhost:8848
        ds1.nacos.data-id: sentinel-flow-rule
        ds1.nacos.rule-type: flow

